// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v1

import (
	"time"
)

// Assignment defines model for Assignment.
type Assignment struct {
	Role    EntityID `json:"role"`
	Scope   string   `json:"scope"`
	Subject string   `json:"subject"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewRole defines model for NewRole.
type NewRole struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// NewRoleAssignment defines model for NewRoleAssignment.
type NewRoleAssignment struct {
	Scope   string `json:"scope"`
	Subject string `json:"subject"`
}

// Permission defines model for Permission.
type Permission struct {
	Description *string `json:"description,omitempty"`
	Target      string  `json:"target"`
}

// PermissionIdentifier defines model for PermissionIdentifier.
type PermissionIdentifier struct {
	Target string `json:"target"`
}

// Role defines model for Role.
type Role struct {
	CreatedAt   time.Time     `json:"createdAt"`
	Description *string       `json:"description,omitempty"`
	Id          EntityID      `json:"id"`
	Name        string        `json:"name"`
	Permissions *[]Permission `json:"permissions,omitempty"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

// RoleInfo defines model for RoleInfo.
type RoleInfo struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`
	Id          EntityID  `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetAssignmentsParams defines parameters for GetAssignments.
type GetAssignmentsParams struct {
	// Subject subject to return assignments for
	Subject string `form:"subject" json:"subject"`

	// Scope scope to return assignments for
	Scope string `form:"scope" json:"scope"`

	// Role role to return assignments for
	Role *EntityID `form:"role,omitempty" json:"role,omitempty"`
}

// GetPermissionsParams defines parameters for GetPermissions.
type GetPermissionsParams struct {
	// Target target to return permission information for
	Target *string `form:"target,omitempty" json:"target,omitempty"`
}

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = NewRole

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = Role

// RemoveRoleAssignmentJSONRequestBody defines body for RemoveRoleAssignment for application/json ContentType.
type RemoveRoleAssignmentJSONRequestBody = NewRoleAssignment

// AssignRoleJSONRequestBody defines body for AssignRole for application/json ContentType.
type AssignRoleJSONRequestBody = NewRoleAssignment

// RemoveRolePermissionJSONRequestBody defines body for RemoveRolePermission for application/json ContentType.
type RemoveRolePermissionJSONRequestBody = PermissionIdentifier

// AddRolePermissionJSONRequestBody defines body for AddRolePermission for application/json ContentType.
type AddRolePermissionJSONRequestBody = PermissionIdentifier
