// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EffectivePermissions string
	GooseDBVersion       string
	Permissions          string
	RoleAssignments      string
	RolePermissions      string
	Roles                string
	TrackedDirectories   string
	TrackedSubjects      string
}{
	EffectivePermissions: "effective_permissions",
	GooseDBVersion:       "goose_db_version",
	Permissions:          "permissions",
	RoleAssignments:      "role_assignments",
	RolePermissions:      "role_permissions",
	Roles:                "roles",
	TrackedDirectories:   "tracked_directories",
	TrackedSubjects:      "tracked_subjects",
}
